discord:
  bot:
    token: ""
    activity:
      type: "PLAYING"
      text: "Minecraft Server"
    minecraft-command-prefix: "!"
  server-id: 0
  global-channel-id: 0
  teams-category-id: 0
  
  account-link:
    verification-timeout: 300 # The time needed to verify the account in seconds (5 minutes) if the value is -1 there is no verification timeout until the server restarts

  notifications:
    connection-messages: true # Notify when a player connects or disconnects from the server
    player-death-messages: true # Notify when a player dies
    advancement-messages: true # Notify when a player gets an advancement
    server-start: true # Notify when the server starts
    server-stop: true # Notify when the server stops

messages:
  en:
    plugin-enabled: "%name% v%version% has been enabled!"
    no-console-command: "Cannot execute this command from the console."
    no-team: "&cYou are not in a team."
    invalid-color: "Invalid team color"

    minecraft-command:
      executed: "The command **/%command%** has been executed."
      not-executed: "The command **/%command%** could not be executed."
      not-found: "The command **/%command%** was not found."
      no-permission: "You do not have the permission to execute this command."
      error: "An error occured while executing this command."

    command:
      no-team-name: "&cYou must specify a team name."
      no-team-tag: "&cYou must specify a team tag."
      team-color-changed: "&fThe team color has been changed to %formated_color%&f."
      team-deleted: "&fThe team %team_color%&l%team% &fhas been deleted."
      team-name-changed: "&fThe team name has been changed from &7&l%old_name% &fto %team_color%&l%new_name%&f."
      team-tag-changed: "&fThe team tag has been changed from &7&l%old_tag% &fto %team_color%&l%new_tag%&f."

    chat:
      minecraft-format: "&6&l[&9&lDiscord&6&l] &c<%username%> &f%message%"
      minecraft-edited-format: "&6&l[&9&lDiscord&6&l] &c<%username%> &f%message% &7&l(Edited)"
      discord-format: "```<%username%> %message%```"
    linking:
      no-linked-account: "Your discord account have not been linked with minecraft, please use the command **/team discordlink <discord-username>** to link it."
      minecraft:
        link-reset: "&fThe verification code for the account &6&l%account% &fhas been reset."
        verfication-code: "&fThe verification code for the account is &6&l%code%&f, please send it to the bot in a private message. You have %timeout% seconds to send the code."
        user-not-found: "&fThe discord user &6&l%account% &fwas not found."
        link-success: "&fDiscord account &6&l%account% &fhas been linked to your minecraft account. To unlink it, use the command **/team discordunlink** or just type **unlink** here."
        unlink-success: "&fDiscord account &6&l%account% &fhas been unlinked from your minecraft account."
        no-discord-account: "&fYou have not a linked discord account"
      bot:
        linking-attempt: "The minecraft player '%player%' is trying to link to this discord account. Please ignore it or send the verification code provided to link."
        invalid-code-format: "The code provided is invalid, please try again."
        link-success: "The minecraft player '%player%' has been linked to your discord account."
        unlink-success: "The minecraft player '%player%' has been unlinked from your discord account."
        unlink-no-account: "You have not a linked minecraft account"
        code-expired: "The code provided has expired, please create a new one."
        invalid-code: "The code you entered is invalid."
        no-link-code: "You have not generated a code yet, please use the command **/team discordlink <discord-username>** to generate one."
        no-minecraft-account: "You have not a linked minecraft account"
    player:
      connected: "The player **%player%** has connected to the server."
      disconnected: "The player **%player%** has disconnected from the server."
      advancement-gained: "**%player%** has gained the advancement **%advancement%**."
    server:
      start: "The server has started."
      stop: "The server has stopped."